### ISSUE TITLE
iOS Build fails after adding Googles Maps 2.2.0 SDK

### ISSUE THREAD

**Issue by Flixt** [mapsplugin/cordova-plugin-googlemaps-sdk#1]
It seems that the commit https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk/commit/4de7ae69fa092766d9f69095b3aad05859ac1d49 introduced a regression.
When trying to build a fresh ionic app with the cordova-plugin-googlemaps plugin added
it fails with the following error message:

```
** BUILD FAILED **


The following build commands failed:

    CompileC /Users/username/Library/Developer/Xcode/DerivedData/MyApp-cxkqzxbgbeswvgaasutfvnvzgpoa/Build/Intermediates/MyApp.build/Debug-iphonesimulator/MyApp.build/Objects-normal/x86_64/Circle.o MyApp/Plugins/cordova-plugin-googlemaps/Circle.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/username/workspace/MyApp-app/platforms/ios/cordova/build-debug.xcconfig,-workspace,MyApp.xcworkspace,-scheme,MyApp,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone 5s,build,CONFIGURATION_BUILD_DIR=/Users/username/workspace/MyApp-app/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/username/workspace/MyApp-app/platforms/ios/build/sharedpch
``` 

Cordova-Version: 6.5.0
Plugin-Version: https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk/commit/4de7ae69fa092766d9f69095b3aad05859ac1d49 (latest master as of time writing)

If I manually checkout the com.googlemap.ios dependency (this repository) and go back to 
f346dd1efebea7af732f89afbda0cc44f1425e67 it builds fine after removing&adding the platform ios. When I open XCode after the build failed, it complains that it can not find UIKit/UIKit.h in several files.

**Comment by wf9a5m75** [comment]
Um, I have no problem with https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk/commit/4de7ae69fa092766d9f69095b3aad05859ac1d49

> it complains that it can not find UIKit/UIKit.h in several files.

It seems UIKitFramework is missing in your environment
https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk/blob/master/plugin.xml#L25

**Comment by wf9a5m75** [comment]
Sorry for late.
I fixed the file structures.

**Comment by wf9a5m75** [comment]
Please reinstall the sdk & plugins like this.

The below command steps are for Cordova 7.0.

```bash
$> npm cache clean

$> cordova create myApp org.apache.cordova.myApp myApp

$> cd myApp

$> cordova platform add ios  //install the platform first for just in case

// If you get the below error, just ignore. And try again.
Error: Failed to fetch platform cordova-ios@~4.4.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Failed to get absolute path to installed module

$> cordova platform add ios

// Add the SDK plugin at first with --nofetch option
$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk --nofetch

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_IOS="(API key)"
```
