### ISSUE TITLE
Update to Google Maps 2.3.0

### ISSUE THREAD

**Issue by bentomas** [mapsplugin/cordova-plugin-googlemaps-sdk#2]
Looks like the latest version of the Google Maps SDK for iOS is at 2.3.0.  At least that's the one it offers here: https://developers.google.com/maps/documentation/ios-sdk/start

**Comment by wf9a5m75** [comment]
Merged! Thank you for sending the update, and I'm sorry for late action. I noticed your pull request yesterday actually.
