### ISSUE TITLE
Not able to install the plugin in MacOS - npm permission issue

### ISSUE THREAD

**Issue by franzisk** [mapsplugin/cordova-plugin-googlemaps-sdk#4]
Hi there,

I am trying to install multiple-maps on a **Ionic v3 app**, Android installed successfully but for iOS it is trying to clone to **/Users/(MY_USER)/.npm/_cacache/tmp/(SOME_FOLDER)** and always says:

`/Users/(MY_USER)/.npm/_cacache/tmp/(SOME_FOLDER)/.git: Permission denied`

I have set permission 777 to this /Users/(MY_USER)/.npm/_cacache/tmp but still having same problem.

The complete command line is:
`sudo cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="MY_ANDROID_KEY" --variable API_KEY_FOR_IOS="MY_IOS_KEY"
`

Is there a way to clone this to other directory?

How could solve this?

**Comment by wf9a5m75** [comment]
Try to install with `--no-fetch` option.

**Comment by franzisk** [comment]
Do you mean?

**$ sudo cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="MY_ANDROID_KEY" --variable API_KEY_FOR_IOS="MY_IOS_KEY" --no-fetch**

Same error:

**Plugin "cordova-plugin-googlemaps" already installed on android.
Installing "cordova-plugin-googlemaps" for ios
Failed to install 'cordova-plugin-googlemaps': Error
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:205:33
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:864:24)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:890:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:808:41)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Error: Failed to fetch plugin https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git /Users/francisco/.npm/_cacache/tmp/git-clone-bfd33e2d
npm ERR! /Users/francisco/.npm/_cacache/tmp/git-clone-bfd33e2d/.git: Permission denied**

**Comment by wf9a5m75** [comment]
Um, I see.

The error log says the git command can not write files into`/Users/francisco/.npm/_cacache/tmp/git-clone-bfd33e2d/` directory.

Please try

```
$> sudo chmod  -R  0777 /Users/francisco/.npm/_cacache/

$> npm clear cache

// no sudo
$> cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="MY_ANDROID_KEY" --variable API_KEY_FOR_IOS="MY_IOS_KEY" --no-fetch
```

**Comment by franzisk** [comment]
Just did, still the same result.

I don't get it why this clone has to be done inside that npm tmp directory. It seems that the "user" that tries to create that random folder is not allowed to create a folder there, how is that possible if I just set all permissions for everyone on that folder?

When I run:
`$ ls -al /Users/francisco/.npm/_cacache`                                                                                   

I get:

```
total 16
drwxrwxrwx    4 root       staff    136 23 Jul 13:44 .
drwxrwxrwx  975 777        staff  33150 23 Jul 13:42 ..
-rw-r--r--@   1 francisco  staff   6148 23 Jul 13:44 .DS_Store
drwxrwxrwx    2 root       staff     68 23 Jul 13:43 tmp
```

**Comment by wf9a5m75** [comment]
The maps plugin specifies to install the SDK plugin from github URL, because the files are very large. The npm does not accept such large files.
That's why npm do git clone inside the npm folder.

Similar issues are reported in couple of days. I think the npm version or cordova version are related with these issues.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1579
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1578


Other solution is install from local folder.

```
$> git clone https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk

$> cd (your app folder)

$> cordova plugin add (path to the cordova-plugin-googlemaps-sdk)

$> cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="MY_ANDROID_KEY" --variable API_KEY_FOR_IOS="MY_IOS_KEY" --no-fetch
```

**Comment by franzisk** [comment]
Thank you very much for you help.

I just did as you said to install from local folder, please have a look and say I did it correctly:

```
% sudo cordova plugin add ~/Projetos-Ionic/v2/cordova-plugin-googlemaps-sdk                                      Installing "com.googlemaps.ios" for android
Installing "com.googlemaps.ios" for ios
Adding com.googlemaps.ios to package.json
Saved plugin info for "com.googlemaps.ios" to config.xml
```

Then I ran the other command, but at this one I am not sure if I got the correct result:

```
% sudo cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="(android key)" --variable API_KEY_FOR_IOS="(iOS key)" --no-fetch
Plugin "cordova-plugin-googlemaps" already installed on android.
Installing "cordova-plugin-googlemaps" for ios
Plugin dependency "com.googlemaps.ios@2.3.0" already fetched, using that version.
Dependent plugin "com.googlemaps.ios" already installed on ios.

             In order to run this plugin, you need to obtain Google Maps API key for iOS.
             Visit https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/Installation/README.md

Adding cordova-plugin-googlemaps to package.json
Saved plugin info for "cordova-plugin-googlemaps" to config.xml
```

Again, thanks for your help

**Comment by wf9a5m75** [comment]
Do you worry about `Dependent plugin "com.googlemaps.ios" already installed on ios`?

It's safely OK.

**Comment by franzisk** [comment]
Right, thank you, it seems that it is installed now.

I am testing on an Android device but it is not showing the map, any ideas what could be?

```
this.map = new GoogleMap('map', {
      'controls': {
        'compass': true,
        'myLocationButton': true,
        'indoorPicker': true,
      },
      'gestures': {
        'scroll': true,
        'tilt': true,
        'rotate': true,
        'zoom': true
      }
    });

    this.map.on(GoogleMapsEvent.MAP_READY).subscribe(() => {
      console.log('Map is ready!');
    });
```

I can see on console the message "**Map is ready!**", I run with:
**sudo ionic cordova run android --livereload -cs**

My config.xml:
```
...
    <engine name="android" spec="^6.2.3" />
    <engine name="ios" spec="^4.4.0" />
    <plugin name="com.googlemaps.ios" spec="/Users/francisco/Projetos-Ionic/v2/cordova-plugin-googlemaps-sdk" />
    <plugin name="cordova-plugin-console" spec="^1.0.5" />
    <plugin name="cordova-plugin-device" spec="^1.1.4" />
    <plugin name="cordova-plugin-geolocation" spec="^2.4.3">
        <variable name="GEOLOCATION_USAGE_DESCRIPTION" value=" " />
    </plugin>
    <plugin name="cordova-plugin-googlemaps" spec="^1.4.3">
        <variable name="API_KEY_FOR_ANDROID" value="(android key)" />
        <variable name="API_KEY_FOR_IOS" value="(iOS key)" />
        <variable name="NSLOCATIONWHENINUSEUSAGEDESCRIPTION" value="Show your location on the map" />
        <variable name="NSLOCATIONALWAYSUSAGEDESCRIPTION" value="Trace your location on the map" />
    </plugin>
    <plugin name="cordova-plugin-splashscreen" spec="^4.0.3" />
    <plugin name="cordova-plugin-statusbar" spec="^2.2.2" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.1" />
    <plugin name="io.litehelpers.cordova.sqlite" spec="~0.7.10" />
    <plugin name="ionic-plugin-keyboard" spec="^2.2.1" />
...
```

**Comment by wf9a5m75** [comment]
Where did you find this code?
```ts
new GoogleMap('map', {
```

At least, [the (old) ionic native page](https://ionicframework.com/docs/native/google-maps/) says

```ts
 let element: HTMLElement = document.getElementById('map');

 let map: GoogleMap = this.googleMaps.create(element);

 // listen to MAP_READY event
 // You must wait for this event to fire before adding something to the map or modifying it in anyway
 map.one(GoogleMapsEvent.MAP_READY).then(
   () => {
     console.log('Map is ready!');
     // Now you can add elements to the map like the marker
   }
 );

```

And the current ionic page is old. Check out the latest document from here.
https://ionic-site-staging.herokuapp.com/docs/native/google-maps/

The plugin v1 and v2 are completely different code. Don't use the v1 code.

**Comment by franzisk** [comment]
I followed this tip:
https://www.joshmorony.com/integrating-native-google-maps-into-an-ionic-2-application/

**Comment by wf9a5m75** [comment]
I see. This is for v1.4, not v2.0.

**Comment by wf9a5m75** [comment]
I sent an e-mail to Josh, so I hope he update the article soon.

And the official document (but it does not use the ionic wrapper) is available here.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/README.md

**Comment by franzisk** [comment]
Well, I changed my script to be exactly like that on the documentation page but still not showing the map on Android/Samsung/S5 device. Only blank screen.

Bellow is my code now:
```
  ngAfterViewInit() {
    console.log('---- Loading the map ------');
    this.loadMyMap();
  }
  
  loadMyMap(): void {
    // create a new map by passing HTMLElement
    let element: HTMLElement = document.getElementById('map');
    let map: GoogleMap = this.googleMaps.create(element);

    // listen to MAP_READY event
    map.one(GoogleMapsEvent.MAP_READY).then(() => {
      console.log('My Map is ready!');
      // Now you can add elements to the map like the marker
    });

    // create CameraPosition
    let position: CameraPosition = {
      target: {
        lat: 43.0741904,
        lng: -89.3809802
      },
      zoom: 18,
      tilt: 30
    };

    // move the map's camera to position
    map.moveCamera(position);
}
```

![blank-map-ionic-v3-android](https://user-images.githubusercontent.com/5133264/28537375-ffa575b0-7080-11e7-988a-32bca5c349ae.png)

Now I see the map box but still can't see the map itself, to be sure I did a restart on the device, no good.

Anything else could cause this?

**Comment by wf9a5m75** [comment]
Don't use `ngAfterViewInit`
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1573#issuecomment-317500353

**Comment by franzisk** [comment]
When I change the code to:
```
constructor(public navCtrl: NavController, public navParams: NavParams, public platform: Platform, private googleMaps: GoogleMaps) {
    platform.ready().then(() => {
      this.loadMyMap();
    });
  }

  loadMyMap(): void {
    // create a new map by passing HTMLElement
    let element: HTMLElement = document.getElementById('map');
    let map: GoogleMap = this.googleMaps.create(element);

    // listen to MAP_READY event
    map.one(GoogleMapsEvent.MAP_READY).then(() => {
      console.log('My Map is ready!');
      // Now you can add elements to the map like the marker
    });

    // create CameraPosition
    let position: CameraPosition = {
      target: {
        lat: 43.0741904,
        lng: -89.3809802
      },
      zoom: 18,
      tilt: 30
    };

    // move the map's camera to position
    map.moveCamera(position);
}
```
Nothing is displayed, not even that empty map box. I had tried that before.

On the console I can see the "My Map is ready!"

**Comment by wf9a5m75** [comment]
At least your code has to 

```ts

constructor(public navCtrl: NavController, public navParams: NavParams, public platform: Platform, private googleMaps: GoogleMaps) {
    platform.ready().then(() => {
      this.loadMyMap();
    });
  }

  loadMyMap(): void {
    // create a new map by passing HTMLElement
    let element: HTMLElement = document.getElementById('map');
    let map: GoogleMap = this.googleMaps.create(element);

    // listen to MAP_READY event
    map.one(GoogleMapsEvent.MAP_READY).then(() => {
      console.log('My Map is ready!');
      // Now you can add elements to the map like the marker

      // create CameraPosition
      let position: CameraPosition = {
        target: {
          lat: 43.0741904,
          lng: -89.3809802
        },
        zoom: 18,
        tilt: 30
      };

      // move the map's camera to position
      map.moveCamera(position);

    });

}
```

**Comment by wf9a5m75** [comment]
I noticed that the document page shows incorrect example... :(

**Comment by wf9a5m75** [comment]
Try this code:

```ts
import {
 GoogleMaps,
 GoogleMap,
 GoogleMapsEvent,
 GoogleMapOptions,
 LatLng,
 CameraPosition,
 MarkerOptions,
 Marker
} from '@ionic-native/google-maps';
import { Component } from "@angular/core/";

import { Platform } from 'ionic-angular';
@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  map: GoogleMap;
  mapElement: HTMLElement;
  constructor(private googleMaps: GoogleMaps, public platform: Platform) {

    platform.ready().then(() => {
      this.loadMap();
    });
  }

  // Load map only after view is initialized
  ngAfterViewInit() {
   //this.loadMap();
  }

 loadMap() {
    this.mapElement = document.getElementById('map');

    let mapOptions: GoogleMapOptions = {
      camera: {
        target: {
          lat: 43.0741904,
          lng: -89.3809802
        },
        zoom: 18,
        tilt: 30
      }
    };

    this.map = this.googleMaps.create(this.mapElement, mapOptions);

    // Wait the MAP_READY before using any methods.
    this.map.one(GoogleMapsEvent.MAP_READY)
      .then(() => {
        console.log('Map is ready!');

        // Now you can use all methods safely.
        this.map.addMarker({
            title: 'Ionic',
            icon: 'blue',
            animation: 'DROP',
            position: {
              lat: 43.0741904,
              lng: -89.3809802
            }
          })
          .then(marker => {
            marker.on(GoogleMapsEvent.MARKER_CLICK)
              .subscribe(() => {
                alert('clicked');
              });
          });

      });
  }
}

```

**Comment by wf9a5m75** [comment]
![screen shot 2017-07-24 at 11 26 44 am](https://user-images.githubusercontent.com/167831/28538402-fd26f23c-7062-11e7-97a5-8285c4bfcf2c.png)

**Comment by franzisk** [comment]
Just did:
```
 map: GoogleMap;
  mapElement: HTMLElement;

  constructor(public navCtrl: NavController, public navParams: NavParams, public platform: Platform, private googleMaps: GoogleMaps) {
    platform.ready().then(() => {
      this.loadMyMap();
    });
  }

  loadMyMap(): void {
    this.mapElement = document.getElementById('map');
    
    let mapOptions: GoogleMapOptions = {
      camera: {
        target: {
          lat: 43.0741904,
          lng: -89.3809802
        },
        zoom: 18,
        tilt: 30
      }
    };
    
    this.map = this.googleMaps.create(this.mapElement, mapOptions);

    // Wait the MAP_READY before using any methods.
    this.map.one(GoogleMapsEvent.MAP_READY).then(() => {
        console.log('Map is ready!');

        // Now you can use all methods safely.
        this.map.addMarker({
          title: 'Ionic',
          icon: 'blue',
          animation: 'DROP',
          position: {
            lat: 43.0741904,
            lng: -89.3809802
          }
        }).then(marker => {
            marker.on(GoogleMapsEvent.MARKER_CLICK)
              .subscribe(() => {
                alert('clicked');
              });
          });

      });

  }
```

Uninstalled the app, restarted the device, **still showing only the black screen.**

's gotta be something else then, how about certificate? private key? anything about this? because I used a SHA-1 certificate fingerprint on the API Key?

**Comment by wf9a5m75** [comment]
>the black screen

Could you show me the screen capture?

**Comment by franzisk** [comment]
Yes
![blank-screen](https://user-images.githubusercontent.com/5133264/28539128-09b8d6f4-7087-11e7-891f-706d4ccd3258.png)

**Comment by wf9a5m75** [comment]
Is there any message in console.log?
If no, please share your project files on github or bitbucket.

I guess you are something wrong.

**Comment by franzisk** [comment]
I really appreciate your help, but I can not share the project online because it's a huge private project and they don't allow to share it.

Burning my brain here to find out what is so wrong with this map, I remember that in the Ionic v1 was a little bit hard to set the map but this one is terrible hard.

**Comment by wf9a5m75** [comment]
I strongly recommend you should test the maps v2 with an empty app. Don't use it in your product app at first.

**Comment by franzisk** [comment]
Will do that

**Comment by wf9a5m75** [comment]
Here
https://github.com/mapsplugin/ionic-google-maps

**Comment by franzisk** [comment]
Hi,

What do you mean by "maps v2"? Where can I check this version?

Anyway, I will start a blank project to test this map separately and see what happens.

Another question, what if I want to use the JavaScript SDK? As before?

**Comment by wf9a5m75** [comment]
I create a plugin for cordova framework itself, not for ionic.
The Ionic framework uses the cordova framework internally.
That's why this map plugin works with the ionic framework.

But the ionic team wants to create TypeScript version instead of pure JavaScript, SL they created own version. That is the Google Maps plugin of ionic-native.

My plugin version is currently the v2.0-beta2.

**Comment by wf9a5m75** [comment]
The maps plugin works with the Google Maps JavaScript API v3.

**Comment by wf9a5m75** [comment]
I appreciate if you search your questions by Google or in the past issues before asking to me.

https://github.com/mapsplugin/cordova-plugin-googlemaps/issues?utf8=✓&q=

**Comment by franzisk** [comment]
Ok my friend, thanks a lot for your help.

I created a new project and started it over, then I followed this link to remove and add again the plugin, and now it's working :)

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v2.0.0/Installation
