### ISSUE TITLE
New version for support new SDK 3.1.0

### ISSUE THREAD

**Issue by RomanPoschl** [mapsplugin/cordova-plugin-googlemaps-sdk#5]
Hi. I love your work. I am using this plugin with your maps plugin and it's awesome. But some last builds don't work. I think its because I use new version of main plugin which by change log support SDK 3.1.0   
Before some last updates in main plugin this plugin was still working.   
Are you planning an update?

**Comment by wf9a5m75** [comment]
If `cordova-cli@9` and `cordova-ios@8`, Cordova installs the Google maps SDK v3. Otherwise installs v2.

**Comment by RomanPoschl** [comment]
I am using Monaca Cloud Build for building the app. And I didn't found some settings where things like that I can set

**Comment by wf9a5m75** [comment]
Please ask to monaca.

**Comment by RomanPoschl** [comment]
Hello,
we just wrote to Monaca support. They told us that:   
"The cordova-ios version used by Monaca is currently v4.5.4. Unfortunately there is no way for users to use other versions at the moment."

What we can do with that? I think we must use older version of your Map plugin.
